[[pages]]
path = "crops/home.py"
name = "Landing Page"
icon = "ğŸ "

[[pages]]
path = "crops/roadgen.py"
name = "Career Path"
icon = "ğŸ—ºï¸"

[[pages]]
path = "crops/chat.py"
name = "Queries"
icon = "ğŸ’¬"

[[pages]]
path = "crops/popular_roadmaps.py"
name = "Popular Paths"
icon = "ğŸ—ºï¸"
