[[pages]]
path = "pages/home.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/roadmap_generator.py"
name = "Roadmap Generator"
icon = "ğŸ—ºï¸"

[[pages]]
path = "pages/chat.py"
name = "Chat"
icon = "ğŸ’¬"

[[pages]]
path = "pages/popular_roadmaps.py"
name = "Popular Roadmaps"
icon = "ğŸ—ºï¸"
