[[pages]]
path = "pages/home.py"
name = "Landing Page"
icon = "ğŸ "

[[pages]]
path = "pages/roadmap_generator.py"
name = "Career Path"
icon = "ğŸ—ºï¸"

[[pages]]
path = "pages/chat.py"
name = "Queries"
icon = "ğŸ’¬"

[[pages]]
path = "pages/popular_roadmaps.py"
name = "Popular Paths"
icon = "ğŸ—ºï¸"
